server:
  port: ${PORT:8080}

spring:
  application:
    name: picpay
  config:
    import: optional:file:.env[.properties]

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

client:
  authorization-service:
    url: https://run.mocky.io/v3/2e2d1021-2a52-40fd-b302-6de708f377a0
  notification-service:
    url: https://run.mocky.io/v3/f5284c67-7894-4abb-b36e-e4a5a2f83755
